---
title: "p8105_hw6_td2749"
author: "Tvisha R. Devavarapu"
date: "2022-11-22"
output: github_document
---

```{r setup, message = FALSE}
library(tidyverse)
library(ggplot2)

knitr::opts_chunk$set(
  fig.width = 10,
  fig.asp = .6,
  out.width = "90%")
```

# Problem 2

```{r homicide_data set up}
homicide_data = 
  read_csv("./data/homicide-data.csv") %>%
  janitor::clean_names() %>% 
  unite(city_state, c(city, state), sep = ",", remove = FALSE) %>% 
  mutate(
    case_stat = ifelse(disposition == "Open/No arrest", 0, 1),
    victim_age = as.numeric(victim_age)) %>% 
  filter(
    !(city_state %in% c("Dallas,TX", "Phoenix,AZ", "Kansas City,MO", "Tulsa,AL")),
    victim_race %in% c("White", "Black"))

head(homicide_data)
```

**Note**: In the `homicide_data` df, column `case_stat` indicates the case status. Cases that are closed by arrest and closed without arrest (solved cases) are represented by 1 and cases that are open/no-arrest (unsolved cases) are represented by 0. 

```{r blatimore glm for logistic fit}
balt_log_fit = 
  homicide_data %>% 
  filter(
    city_state == "Baltimore,MD") %>% 
  glm(case_stat ~ victim_age + victim_sex + victim_race, data = ., family = binomial())

balt_log_fit = broom::tidy(balt_log_fit)


```

